# Command to run: ansible-playbook -K -i inventory.yaml playbook.yaml --tags init --limit workstations

workstations:
  hosts:
    # Hans' workstation
    asiclab000.physik.uni-bonn.de:
      mac: 54:BF:64:98:25:B6
    # to my left
    asiclab001.physik.uni-bonn.de:
      mac: 54:BF:64:98:25:D4
    # next to Snow, saqlain's old desk  
    asiclab002.physik.uni-bonn.de:
      mac: 54:BF:64:98:25:CC
    # behind me, next to saqualin
    asiclab003.physik.uni-bonn.de:
      mac: 54:BF:64:98:25:BA
    # in front of me
    asiclab006.physik.uni-bonn.de:
      mac: 54:BF:64:98:25:F0
    # My computer
    asiclab008.physik.uni-bonn.de:
      mac: 54:BF:64:98:25:ED
    # dominic
    asiclab011.physik.uni-bonn.de:
      mac: 54:BF:64:98:27:03

centos:
  hosts:
    # tomek's old
    asiclab004.physik.uni-bonn.de:
    # marco's old
    asiclab005.physik.uni-bonn.de:
    # next to Dominic, not booting?
    asiclab007.physik.uni-bonn.de:
    # snow
    asiclab009.physik.uni-bonn.de:
    # saqlain
    asiclab010.physik.uni-bonn.de:

# in the electronics room, should maybe be ubuntu?
workstations_old:
  hosts:
    asiclab00.physik.uni-bonn.de:
      mac: 44:37:E6:89:C3:50
    asiclab01.physik.uni-bonn.de:
      mac: 44:37:E6:94:CB:C8
    asiclab02.physik.uni-bonn.de:
      mac: 44:37:E6:94:A6:63
    asiclab05.physik.uni-bonn.de:
      mac: 44:37:E6:94:CB:DE
    asiclab07.physik.uni-bonn.de:
      mac: 44:37:E6:94:A6:5F
    asiclab08.physik.uni-bonn.de:
      mac: 44:37:E6:94:FC:39

misc:
  hosts:
    asiclab06.physik.uni-bonn.de: # under dominik's desk, is windows
    asiclab04.physik.uni-bonn.de: # in Eworkshop, isn't fedora
    asiclabwin001.physik.uni-bonn.de: # running LDAP server, is Fedora
